name: Deploy to GitHub Pages and Heroku

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install frontend dependencies and build
        working-directory: frontend
        run: |
          npm install
          npm run build

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install backend dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install gunicorn
        run: |
          pip install gunicorn

      - name: Start backend server
        working-directory: backend
        run: |
          gunicorn -b 0.0.0.0:5000 main:app  # Replace with your actual startup command

      - name: Deploy frontend to GitHub Pages
        working-directory: frontend
        run: |
          npm run deploy

